project:
  type: website
  output-dir: docs

website:
  title: "Yosuke Kimura"
  site-url: "https://yosukekimura1988.github.io/yosuke-kimura.github.io/"
  navbar:
    left:
      - href: index.qmd
        text: Home
      - href: research.qmd
        text: Research
      - href: projects.qmd
        text: Projects
      - href: teaching.qmd
        text: Teaching
      - href: students.qmd
        text: Students
      - href: igp.qmd
        text: IGP
      - href: cv.qmd
        text: CV
    right:
      - icon: github
        href: https://github.com/yosukekimura1988
      - icon: google
        href: https://scholar.google.com/

format:
  html:
    theme: cosmo
    toc: true
    page-layout: full
